apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-web-%s" (include "bg.name" .) .Values.activeColor | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "bg.labels" . | nindent 4 }}
    component: web
    color: {{ .Values.activeColor }}
spec:
  replicas: {{ .Values.app.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app }}
      component: web
      color: {{ .Values.activeColor }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app }}
        component: web
        color: {{ .Values.activeColor }}
    spec:
      containers:
      - name: web
        image: {{ ternary .Values.app.imageWebGreen .Values.app.imageWebBlue (eq .Values.activeColor "green") | quote }}
        ports:
          - containerPort: {{ .Values.app.containerPortWeb }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.containerPortWeb }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.containerPortWeb }}
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
{{ toYaml .Values.app.resources | indent 10 }}
