# templates/deployment-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluegreen.fullname" . }}-web-{{ .Values.activeColor }}
spec:
  replicas: {{ .Values.app.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "bluegreen.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "bluegreen.fullname" . }}-web
    spec:
      containers:
        - name: web
          image: {{ ternary .Values.app.web.imageGreen .Values.app.web.imageBlue (eq .Values.activeColor "green") | quote }}
          ports:
            - containerPort: {{ .Values.app.web.containerPortWeb }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.web.containerPortWeb }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.web.containerPortWeb }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
{{ toYaml .Values.app.web.resources | indent 10 }}
