# templates/deployment-order.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluegreen.fullname" . }}-order-{{ .Values.activeColor }}
spec:
  replicas: {{ .Values.app.order.replicas }}
  selector:
    matchLabels:
      app: {{ include "bluegreen.fullname" . }}-order
  template:
    metadata:
      labels:
        app: {{ include "bluegreen.fullname" . }}-order
    spec:
      containers:
        - name: order
          image: {{ ternary .Values.app.order.imageGreen .Values.app.order.imageBlue (eq .Values.activeColor "green") | quote }}
          ports:
            - containerPort: {{ .Values.app.order.containerPortOrder }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.order.containerPortOrder }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.order.containerPortOrder }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
{{ toYaml .Values.app.order.resources | indent 10 }}

