apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-order-%s" (include "bg.name" .) .Values.activeColor | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "bg.labels" . | nindent 4 }}
    component: order
    color: {{ .Values.activeColor }}
spec:
  replicas: {{ .Values.app.replicas | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app }}
      component: order
      color: {{ .Values.activeColor }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app }}
        component: order
        color: {{ .Values.activeColor }}
    spec:
      containers:
      - name: order
        image: {{ ternary .Values.app.imageOrderGreen .Values.app.imageOrderBlue (eq .Values.activeColor "green") | quote }}
        ports:
          - containerPort: {{ .Values.app.containerPort }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.containerPort }}
        resources:
{{ toYaml .Values.app.resources | indent 10 }}
