apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-grafana" (include "bg.name" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "bg.labels" . | nindent 4 }}
    component: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app }}
      component: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app }}
        component: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image | quote }}
        ports:
          - containerPort: 3000
        resources:
{{ toYaml .Values.grafana.resources | indent 10 }}
