apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-grafana" (include "bg.name" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "bg.labels" . | nindent 4 }}
    component: grafana
...
