apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bg.name" . }}-db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "{{ .Values.postgres.postgresPassword | default "changeme" }}"
  POSTGRES_USER: "{{ .Values.postgres.postgresUser | default "postgres" }}"
  POSTGRES_DB: "{{ .Values.postgres.postgresDatabase | default "postgres" }}"
