apiVersion: v1
kind: Secret
metadata:
name: {{ include "bg.name" . }}-db-secret
type: Opaque
stringData:
POSTGRES_USER: {{ .Values.postgres.postgresUser | quote }}
POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | quote }}
POSTGRES_DB: {{ .Values.postgres.postgresDatabase | quote }}
