apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-web-svc" (include "bg.name" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "bg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.app.web.containerPortWeb | default 8080  }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.labels.app }}
    color: {{ .Values.activeColor }}
